

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/One-Txc/config-server.git/
server:
  port: 8000

management:
  security:
    enabled: false